on:
  push
jobs:
  patch:
    name: Patch
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Deploy
        run: ./patch.sh
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
